import { MarketplaceItem } from "./types";

export const categories = [
  { id: "business", name: "Business", count: 3 },
  { id: "ecommerce", name: "E-commerce", count: 1 },
  { id: "portfolio", name: "Portfolio", count: 1 },
  { id: "restaurant", name: "Restaurant", count: 1 },
  { id: "blog", name: "Blog", count: 1 },
  { id: "saas", name: "SaaS", count: 1 },
  { id: "contact", name: "Contact", count: 1 },
  { id: "photography", name: "Photography", count: 1 },
  { id: "agency", name: "Agency", count: 1 },
  { id: "testimonials", name: "Testimonials", count: 1 },
  { id: "real-estate", name: "Real Estate", count: 1 },
  { id: "pricing", name: "Pricing", count: 1 },
];

export const marketplaceItems: MarketplaceItem[] = [
  {
    id: "1",
    title: "Modern Business Landing Page",
    description:
      "A sleek and professional landing page template perfect for startups and businesses looking to make a strong first impression.",
    preview: "/placeholder.svg",
    templateType: "page",
    featured: true,
    pageCount: 1,
    tags: ["business", "modern", "landing"],
    downloads: 1247,
    likes: 892,
    author: {
      name: "DesignStudio",
      verified: true,
    },
  },
  {
    id: "2",
    title: "E-commerce Product Showcase",
    description:
      "Complete e-commerce template with product grids, shopping cart, and checkout flow.",
    preview: "/placeholder.svg",
    templateType: "full-site",
    featured: false,
    pageCount: 5,
    tags: ["ecommerce", "shopping", "products"],
    downloads: 2156,
    likes: 1432,
    author: {
      name: "ShopTemplates",
      verified: true,
    },
  },
  {
    id: "3",
    title: "Portfolio Hero Section",
    description:
      "Eye-catching hero section component for creative portfolios and personal websites.",
    preview: "/placeholder.svg",
    templateType: "section",
    featured: false,
    pageCount: undefined,
    tags: ["portfolio", "hero", "creative"],
    downloads: 892,
    likes: 567,
    author: {
      name: "CreativeBlocks",
      verified: false,
    },
  },
  {
    id: "4",
    title: "Restaurant Menu Block",
    description:
      "Beautiful menu display component with categories, prices, and descriptions.",
    preview: "/placeholder.svg",
    templateType: "block",
    featured: false,
    pageCount: undefined,
    tags: ["restaurant", "menu", "food"],
    downloads: 445,
    likes: 234,
    author: {
      name: "FoodieDesigns",
      verified: false,
    },
  },
  {
    id: "5",
    title: "Blog Homepage Template",
    description:
      "Full blog template with featured posts, categories, and responsive design.",
    preview: "/placeholder.svg",
    templateType: "page",
    featured: true,
    pageCount: 1,
    tags: ["blog", "content", "responsive"],
    downloads: 1876,
    likes: 1234,
    author: {
      name: "ContentCreators",
      verified: true,
    },
  },
  {
    id: "6",
    title: "SaaS Dashboard UI Kit",
    description:
      "Complete dashboard interface with charts, tables, and navigation components.",
    preview: "/placeholder.svg",
    templateType: "full-site",
    featured: false,
    pageCount: 8,
    tags: ["saas", "dashboard", "ui-kit"],
    downloads: 3241,
    likes: 2156,
    author: {
      name: "UIToolkit",
      verified: true,
    },
  },
  {
    id: "7",
    title: "Contact Form Section",
    description:
      "Professional contact form with validation and multiple input types.",
    preview: "/placeholder.svg",
    templateType: "section",
    featured: false,
    pageCount: undefined,
    tags: ["contact", "form", "validation"],
    downloads: 678,
    likes: 345,
    author: {
      name: "FormMasters",
      verified: false,
    },
  },
  {
    id: "8",
    title: "Photography Gallery Block",
    description:
      "Responsive image gallery with lightbox and filtering capabilities.",
    preview: "/placeholder.svg",
    templateType: "block",
    featured: false,
    pageCount: undefined,
    tags: ["photography", "gallery", "lightbox"],
    downloads: 923,
    likes: 678,
    author: {
      name: "PhotoBlocks",
      verified: false,
    },
  },
  {
    id: "9",
    title: "Agency Services Page",
    description:
      "Showcase your agency's services with this clean and professional template.",
    preview: "/placeholder.svg",
    templateType: "page",
    featured: false,
    pageCount: 1,
    tags: ["agency", "services", "professional"],
    downloads: 1456,
    likes: 987,
    author: {
      name: "AgencyTemplates",
      verified: true,
    },
  },
  {
    id: "10",
    title: "Testimonial Carousel",
    description:
      "Interactive testimonial slider with customer reviews and ratings.",
    preview: "/placeholder.svg",
    templateType: "block",
    featured: false,
    pageCount: undefined,
    tags: ["testimonials", "carousel", "reviews"],
    downloads: 567,
    likes: 432,
    author: {
      name: "ReviewComponents",
      verified: false,
    },
  },
  {
    id: "11",
    title: "Real Estate Listing Site",
    description:
      "Complete real estate website with property listings, search, and details pages.",
    preview: "/placeholder.svg",
    templateType: "full-site",
    featured: true,
    pageCount: 12,
    tags: ["real-estate", "listings", "property"],
    downloads: 2891,
    likes: 1876,
    author: {
      name: "PropertySites",
      verified: true,
    },
  },
  {
    id: "12",
    title: "Pricing Table Section",
    description:
      "Flexible pricing table component with multiple plans and feature comparisons.",
    preview: "/placeholder.svg",
    templateType: "section",
    featured: false,
    pageCount: undefined,
    tags: ["pricing", "comparison", "plans"],
    downloads: 1123,
    likes: 789,
    author: {
      name: "PricingPro",
      verified: false,
    },
  },
];
