import { CustomComponent } from "../styleconstants";
import { v4 as uuidv4 } from "uuid";

export const buttonMultiComponent: CustomComponent = {
  component: {
    type: "Button",
    name: "Button Multi",
    buttonType: "multi",
    content: "Dropdown",
    isSelected: false,
    isHovered: false,
    isDraggedOver: false,
    x: 0,
    y: 0,
    id: uuidv4(),
    href: "",
    src: "",
    parentId: "",
    projectId: "",
    tailwindStyles:
      "flex items-center justify-between px-4 py-2 rounded-md bg-gradient-to-r from-blue-600 to-blue-500 text-white hover:from-blue-700 hover:to-blue-600 shadow-md transition-all duration-200",
    styles: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      width: "200px",
      padding: "8px 16px",
      backgroundColor: "#3b82f6",
      color: "#ffffff",
      cursor: "pointer",
      fontWeight: "500",
      borderRadius: "6px",
      border: "none",
      boxShadow: "0 2px 5px rgba(0,0,0,0.15)",
      transition: "all 0.2s ease",
      fontSize: "14px",
    },
    element: {
      type: "Frame",
      name: "Dropdown Content",
      id: uuidv4(),
      content: "",
      isSelected: false,
      isHovered: false,
      isDraggedOver: false,
      x: 0,
      y: 0,
      href: "",
      src: "",
      parentId: "",
      projectId: "",
      tailwindStyles: "absolute top-full left-0 mt-1 w-full bg-white border border-gray-200 rounded-md shadow-lg overflow-hidden z-10",
      styles: {
        position: "absolute",
        top: "100%",
        left: "0",
        marginTop: "4px",
        display: "none",
        flexDirection: "column",
        width: "100%",
        backgroundColor: "#ffffff",
        border: "1px solid #e5e7eb",
        borderRadius: "6px",
        boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
        padding: "4px",
        gap: "2px",
        overflow: "hidden",
        zIndex: "10",
      },
      elements: [
        {
          type: "Button",
          id: uuidv4(),
          content: "Option 1",
          isSelected: false,
          isHovered: false,
          isDraggedOver: false,
          x: 0,
          y: 0,
          href: "",
          src: "",
          parentId: "",
          projectId: "",
          buttonType: "primary",
          styles: {
            padding: "8px 12px",
            width: "100%",
            textAlign: "left",
            backgroundColor: "transparent",
            color: "#374151",
            border: "none",
            borderRadius: "4px",
            cursor: "pointer",
            transition: "background-color 0.2s",
            fontWeight: "normal",
            fontSize: "14px",
          },
          tailwindStyles:
            "text-gray-700 hover:bg-gray-100 rounded w-full text-left px-3 py-2",
        },
        {
          type: "Button",
          id: uuidv4(),
          content: "Option 2",
          isSelected: false,
          isHovered: false,
          isDraggedOver: false,
          x: 0,
          y: 0,
          href: "",
          src: "",
          parentId: "",
          projectId: "",
          buttonType: "primary",
          styles: {
            padding: "8px 12px",
            width: "100%",
            textAlign: "left",
            backgroundColor: "transparent",
            color: "#374151",
            border: "none",
            borderRadius: "4px",
            cursor: "pointer",
            transition: "background-color 0.2s",
            fontWeight: "normal",
            fontSize: "14px",
          },
          tailwindStyles:
            "text-gray-700 hover:bg-gray-100 rounded w-full text-left px-3 py-2",
        },
        {
          type: "Button",
          id: uuidv4(),
          content: "Option 3",
          isSelected: false,
          isHovered: false,
          isDraggedOver: false,
          x: 0,
          y: 0,
          href: "",
          src: "",
          parentId: "",
          projectId: "",
          buttonType: "primary",
          styles: {
            padding: "8px 12px",
            width: "100%",
            textAlign: "left",
            backgroundColor: "transparent",
            color: "#374151",
            border: "none",
            borderRadius: "4px",
            cursor: "pointer",
            transition: "background-color 0.2s",
            fontWeight: "normal",
            fontSize: "14px",
          },
          tailwindStyles:
            "text-gray-700 hover:bg-gray-100 rounded w-full text-left px-3 py-2",
        },
      ],
    },
  },
};
